name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Backend code formatting check (Black)
        uses: psf/black@stable
      - name : Frontend code formatting check (Prettier)
        uses: creyD/prettier_action@v4.2
        with:
          dry: True
