name: Tests

on:
  push:
    branches:
      - master
      - hotfixes
      - develop
      - Adrien-Pajot-cypress-tests
  pull_request:
    branches:
      - master
      - hotfixes
      - develop

jobs:
  install_all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "Debian 11"
            python-version: "3.9"
            postgres-version: 13
            postgis-version: 3.2

    name: Install on ${{ matrix.name }}

    services:
      postgres:
        image: postgis/postgis:${{ matrix.postgres-version }}-${{ matrix.postgis-version }}
        env:
          POSTGRES_DB: geonature2db
          POSTGRES_PASSWORD: geonatpasswd
          POSTGRES_USER: geonatadmin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Add postgis_raster database extension
      if: ${{ matrix.postgis-version >= 3 }}
      run: |
        psql -h localhost -U geonatadmin -d geonature2db -tc 'CREATE EXTENSION "postgis_raster";'
      env:
        PGPASSWORD: geonatpasswd
    - name: Add database extensions
      run: |
        psql -h localhost -U geonatadmin -d geonature2db -tc 'CREATE EXTENSION "hstore";'
        psql -h localhost -U geonatadmin -d geonature2db -tc 'CREATE EXTENSION "uuid-ossp";'
        psql -h localhost -U geonatadmin -d geonature2db -tc 'CREATE EXTENSION "pg_trgm";'
        psql -h localhost -U geonatadmin -d geonature2db -tc 'CREATE EXTENSION "unaccent";'
      env:
        PGPASSWORD: geonatpasswd
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install GDAL
      run: |
        sudo apt install -y libgdal-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install \
          -e .[tests] \
          -r backend/requirements-common.txt \
          -e file:backend/dependencies/UsersHub-authentification-module#egg=pypnusershub \
          -e file:backend/dependencies/Nomenclature-api-module#egg=pypnnomenclature \
          -e file:backend/dependencies/Habref-api-module#egg=pypn_habref_api \
          -e file:backend/dependencies/TaxHub#egg=taxhub \
          -e file:backend/dependencies/Utils-Flask-SQLAlchemy#egg=utils-flask-sqlalchemy \
          -e file:backend/dependencies/Utils-Flask-SQLAlchemy-Geo#egg=utils-flask-sqlalchemy-geo \
          -e file:backend/dependencies/RefGeo#egg=pypn-ref-geo
    - name: Install database
      run: |
        geonature db upgrade geonature@head -x local-srid=2154
        geonature db autoupgrade -x local-srid=2154
        geonature db upgrade geonature-samples@head
        geonature db upgrade taxonomie_taxons_example@head
        geonature db upgrade ref_geo_fr_departments@head
        geonature db upgrade ref_geo_fr_municipalities@head
        geonature db upgrade ref_geo_inpn_grids_5@head
        geonature db upgrade ref_sensitivity_inpn@head
      env:
        GEONATURE_CONFIG_FILE: config/test_config.toml
    - name: Install core modules
      run: |
        geonature install_packaged_gn_module contrib/occtax OCCTAX --build=false
        geonature install_packaged_gn_module contrib/gn_module_occhab OCCHAB --build=false
        geonature install_packaged_gn_module contrib/gn_module_validation VALIDATION --build=false
      env:
        GEONATURE_CONFIG_FILE: config/test_config.toml
    - name: run GN backend
      run : geonature dev_back &
      env:
        GEONATURE_CONFIG_FILE: config/test_config.toml
    - name: run TX backend
      run : flask run --host=0.0.0.0 &
      working-directory: ./backend/dependencies/TaxHub/
      env:
        TAXHUB_SETTINGS: test_config.py

  test_backend:
    name: Run backend tests
    needs: install_all
    strategy:
      fail-fast: false
    steps:
    - name: Test with pytest
      run: |
        pytest -v --cov --cov-report xml
      env:
        GEONATURE_CONFIG_FILE: config/test_config.toml
    - name: Upload coverage to Codecov
      if: ${{ matrix.name == 'Debian 11' }}
      uses: codecov/codecov-action@v2
      with:
        flags: pytest

  test_frontend:
    name: Run frontend tests
    needs: install_all
    strategy:
      fail-fast: false
    steps:
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        record: true
        working-directory: ./frontend
        start: npm run start-for-ci
        wait-on: http://127.0.0.1:4200
        headless: true
      env: 
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}